FROM centos:centos8

#------------
# GCC default
#------------
RUN yum group install -y -q "Development Tools" && yum clean all
WORKDIR /usr/local/src

#------------
# fpm
#------------
RUN yum -y install ruby ruby-devel ruby-libs rubygems rpm-build \
 && gem install fpm --no-rdoc --no-ri

RUN yum remove -y gcc c++

#----------
# GCC 6.5.0
#----------
COPY ./rpms/opt-gcc-6.5.0.el8.x86_64.rpm opt-gcc-6.5.0.el8.x86_64.rpm
RUN rpm -ivh opt-gcc-6.5.0.el8.x86_64.rpm

# alternatives
RUN update-alternatives \
 --install /usr/bin/gcc gcc /opt/gcc-6.5.0/bin/gcc 20 \
 --slave   /usr/bin/g++ g++ /opt/gcc-6.5.0/bin/g++
ENV CC=/opt/gcc-6.5.0/bin/gcc
ENV CXX=/opt/gcc-6.5.0/bin/g++

# compile check
COPY ./rpms/hello.c hello.c
RUN gcc -v hello.c && ./a.out

#------------
# ENV
#------------
ENV CXXFLAGS="-std=gnu++98"

#----------
# GCC 4.9.4
#----------
COPY gcc-4.9.4.tar.gz gcc-4.9.4.tar.gz
RUN tar xzf gcc-4.9.4.tar.gz
WORKDIR /usr/local/src/gcc-4.9.4/
RUN yum install -y -q wget && yum clean all
RUN ./contrib/download_prerequisites

# --disable-bootstrap
# --enable-bootstrap
RUN ./configure \
 --prefix=/opt/gcc-6.5.0 \
 --with-bugurl=http://bugzilla.redhat.com/bugzilla \
 --disable-bootstrap \
 --enable-shared \
 --enable-threads=posix \
 --enable-checking=release \
 --with-system-zlib \
 --enable-__cxa_atexit \
 --disable-libunwind-exceptions \
 --enable-gnu-unique-object \
 --enable-languages=c,c++ \
 --disable-dssi \
 --enable-libgcj-multifile \
 --with-ppl \
 --with-cloog \
 --with-tune=generic \
 --disable-multilib \
 --build=x86_64-redhat-linux

RUN make -s
RUN make install

RUN fpm -s dir \
  -v 6.5.0 \
  -t rpm \
  -n opt-gcc-4.9.4 \
  -p opt-gcc-4.9.4.el8.x86_64.rpm \
  -C /opt/gcc-4.9.4 \
  --prefix /opt/gcc-4.9.4 \
  -a x86_64 \
  .

# #---------
# # mysql
# #---------
# # ENV PACKAGES="ORBit2-devel"
# # RUN yum install -y -q $PACKAGES && yum clean all
# 
# COPY mysql-4.0.30.tar.gz mysql-4.0.30.tar.gz
# RUN tar xzf mysql-4.0.30.tar.gz
# WORKDIR /usr/local/src/mysql-4.0.30
# # eucjpとsjisを有効化
# RUN ./configure --prefix=/opt/mysql --with-charset=ujis --with-extra-charsets=sjis --quiet
# 
# RUN make -s 1>/dev/null \
#  && make install \
#  && fpm -s dir \
#   -v 4.0.30 \
#   -t rpm \
#   -n opt-mysql4 \
#   -p opt-mysql4-4.0.30.el7.x86_64.rpm \
#   -C /opt/mysql \
#   --prefix /opt/mysql \
#   -a x86_64 \
#   .
# 
# # php
# WORKDIR /usr/local/src/
# 
# #-----
# # re2c
# #-----
# ENV PACKAGES="re2c"
# RUN yum install -y -q $PACKAGES && yum clean all
# 
# #-----
# # lemon
# #-----
# RUN gcc -o /usr/local/bin/lemon lemon.c
# 
# #-----
# # flex
# #-----
# RUN yum install -y -q byacc && yum clean all \
#  && tar xzf flex-2.5.4a.tar.gz \
#  && cd flex-2.5.4 \
#  && ./configure --prefix=/opt/flex \
#  && make -s \
#  && make install \
#  && fpm -s dir \
#   -v 2.5.4a \
#   -t rpm \
#   -n local-flex \
#   -p local-flex-2.5.4a.el7.x86_64.rpm \
#   -C /opt/flex \
#   --prefix /usr/local \
#   -a x86_64 \
#   . \
#  && rpm -ivh local-flex-2.5.4a.el7.x86_64.rpm
# 
# #------
# # bison
# #------
# RUN tar jxf bison-2.4.1.tar.bz2 \
#  && cd bison-2.4.1 \
#  && ./configure \
#  && make -s \
#  && make install \
#  && make install DESTDIR=/opt/bison \
#  && fpm -s dir \
#   -v 2.4.1 \
#   -t rpm \
#   -n local-bison \
#   -p local-bison-2.4.1.el7.x86_64.rpm \
#   -C /opt/bison \
#   --prefix /usr/local \
#   -a x86_64 \
#   .
# 
# # php
# RUN tar jxf php-5.2.17.tar.bz2
# 
# # configureを通すため。
# RUN ln -s /opt/mysql/lib/mysql/libmysqlclient.so /opt/mysql/lib/mysql/libmysqlclient_r.so \
#  && ln -s /opt/mysql/lib/mysql/libmysqlclient.a /opt/mysql/lib/mysql/libmysqlclient_r.a \
#  && ln -s /opt/mysql/lib /opt/mysql/lib64
# 
# # patch
# WORKDIR /usr/local/src/php-5.2.17
# RUN patch -p0 -b < ../php-patch/php-5.2.17.patch \
#  && patch -p0 -b < ../php-patch/gmp.patch \
#  && patch -p0 -b < ../php-patch/php_functions.patch
# RUN ./configure --quiet \
#   --prefix=/usr/local/php \
#   --with-apxs2=/usr/bin/apxs \
#   --with-pear=/usr/local/pear \
#   --disable-cgi \
#   --enable-zend-multibyte \
#   --enable-mbstring \
#   \
#   --with-mysql=shared,/opt/mysql \
#   --with-pdo-mysql=shared,/opt/mysql \
#   \
#   --with-openssl \
#   --with-mhash=shared,/usr \
#   --with-mcrypt=shared,/usr \
#   --enable-sockets \
#   --enable-pcntl \
#   --enable-sigchild \
#   --with-gd=shared \
#   --with-jpeg-dir=/usr \
#   --with-png-dir=/usr \
#   --with-zlib \
#   --with-zlib-dir=/usr \
#   --with-ttf \
#   --with-freetype-dir=/usr \
#   --enable-gd-native-ttf \
#   --enable-gd-jis-conv \
#   \
#   --with-config-file-path=/etc/ --with-config-file-scan-dir=/etc/php.d \
#   \
#   --with-libdir=lib64 \
#   1>/dev/null
# 
# RUN make -s 1>/dev/null
# RUN make test 1>/dev/null
# # /etc/httpd/conf/httpd.confがhttpdパッケージとconfrictするため除外
# RUN make install
# RUN fpm -s dir \
#   -v 5.2.17 \
#   -t rpm \
#   -n local-php \
#   -p local-php-5.2.17.el7.x86_64.rpm \
#   -C /usr/local \
#   --prefix /usr/local \
#   -a x86_64 \
#   php pear
# 
# 
# #---------
# # local-pear
# #---------
# RUN /usr/local/php/bin/pear install DB-1.7.14 \
#  && /usr/local/php/bin/pear install Var_Dump
# 
# WORKDIR /usr/local
# RUN mkdir -p /root/rpmbuild/SOURCES /root/rpmbuild/BUILD /root/rpmbuild/SPECS \
#  && tar czf $BUILDROOT/SOURCES/local-pear.tar.gz pear php/bin/pear php/bin/peardev php/bin/gen_php_doc.sh \
#  && tar xzf $BUILDROOT/SOURCES/local-pear.tar.gz -C $BUILDROOT/BUILD/
# 
# WORKDIR $BUILDROOT/
# RUN cp /usr/local/src/local-pear.spec $BUILDROOT/SPECS/ \
#  && rpmbuild -ba SPECS/local-pear.spec
# 
# #---------------
# # opt-ruby-1.8.7
# #---------------
# WORKDIR $BUILDROOT/SOURCES/
# # http://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p374.tar.bz2
# COPY files.centos7/ruby-1.8.7-p374.tar.bz2 .
# RUN tar xf ruby-1.8.7-p374.tar.bz2
# WORKDIR $BUILDROOT/SOURCES/ruby-1.8.7-p374
# # https://www.ruby-forum.com/topic/142608
# RUN yum install -y -q tk-devel tclx
# COPY files.centos7/ruby-1.8.7-p374-openssl.patch .
# # openssl patch : https://gist.github.com/alanthing/1a151c9d8d0b81f039d3
# RUN patch -p1 < ruby-1.8.7-p374-openssl.patch
# RUN ./configure --prefix=/opt/ruby --enable-pthread \
#  && make -s \
#  && make test \
#  && make install
# RUN fpm -s dir \
#   -v 1.8.7_p374 \
#   -t rpm \
#   -n opt-ruby \
#   -p opt-ruby-1.8.7-p374.el7.x86_64.rpm \
#   -C /opt/ruby \
#   --prefix / \
#   -a x86_64 \
#   .
# 
# WORKDIR /usr/local/src/ruby
# # mysql-ruby
# RUN tar xzf mysql-ruby-2.8.2.tar.gz \
#  && cd mysql-ruby-2.8.2 \
#  && /opt/ruby/bin/ruby extconf.rb --with-mysql-dir=/opt/mysql \
#  && make -s \
#  && make install
# # rpmbuild
# WORKDIR /usr/local/src/ruby
# COPY files.centos7/mysql-ruby.spec $BUILDROOT/SPECS/
# RUN tar czf $BUILDROOT/SOURCES/mysql-ruby-2.8.2.tar.gz /opt/ruby/lib/ruby/site_ruby/1.8/x86_64-linux/mysql.so \
#  && rpmbuild -ba $BUILDROOT/SPECS/mysql-ruby.spec
# 
# # ruby-dbi 0.1.1
# WORKDIR /usr/local/src/ruby
# RUN tar xzf rel-0-1-1.tar.gz \
#  && cd ruby-dbi-rel-0-1-1 \
#  && /opt/ruby/bin/ruby setup.rb config --with=dbi,dbd_mysql \
#  && /opt/ruby/bin/ruby setup.rb setup \
#  && /opt/ruby/bin/ruby setup.rb install
# # rpmbuild
# WORKDIR /usr/local/src/ruby
# COPY files.centos7/ruby-dbi-0.1.1.spec $BUILDROOT/SPECS/
# RUN tar czf $BUILDROOT/SOURCES/ruby-dbi-0.1.1.tar.gz /opt/ruby/lib/ruby/site_ruby/1.8 /opt/ruby/bin/sqlsh.rb \
#  && rpmbuild -ba $BUILDROOT/SPECS/ruby-dbi-0.1.1.spec
